- MANIFEST.in
Fixes https://github.com/coala-analyzer/coala-quickstart/issues/10
> MANIFEST.in: Add it

- coala_quickstart/coala_quickstart.py
This is also already testable with `py.test --doctest-modules`
> coala-quickstart: Ask user for dir

- coala_quickstart/all.coafile
We'll pull in sections from that and all sections that have globs that
match files should be taken into consideration for the users coafile.
> Add all.coafile

- .ci/deps.sh
- .ci/env_variables.sh
- .ci/tests.sh
- circle.yml
- setup.cfg
- setup.py
- test-requirements.txt
> CI: Add files necessary for ci

- coala_quickstart/coala_quickstart.py
- coala_quickstart/generation/FileGlobs.py
- coala_quickstart/generation/Settings.py
- coala_quickstart/generation/Utilities.py
- requirements.txt
- setup.cfg
- tests/generation/Bears.py
- tests/generation/FileGlobs.py
> Lots of new stuff: Part 2

- circle.yml
- setup.py
Closes https://github.com/coala/coala-quickstart/issues/35
> Drop Python 3.3 support

- coala_quickstart/coala_quickstart.py
- coala_quickstart/generation/Bears.py
Fixes https://github.com/coala/coala-quickstart/issues/39
> Adds zero configuration mode argument --ci

- coala_quickstart/coala_quickstart.py
Closes https://github.com/coala/coala-quickstart/issues/51
> Disable welcome message in non-interactive mode

- README.rst
> README: Remove perfection

- coala_quickstart/Constants.py
This disables coalabear
Fix https://github.com/coala/coala-quickstart/issues/44
> Constants.py: Deactivate 'coalabear'

- coala_quickstart/Strings.py
Changing 'coala-analyzer' to 'coala'.
Closes https://github.com/coala/coala-quickstart/issues/75
> Strings.py: Update URL's

- .ci/appveyor.yml
- .ci/run_with_env.cmd
- coala_quickstart/generation/Project.py
- tests/generation/FileGlobs.py
Adds Appveyor configuration files for CI on windows.
Related to https://github.com/coala/coala-quickstart/issues/22
> gsoc: Add Appveyor

- .travis.yml
Adds Travis CI for Continuous Integration on OSX.
> gsoc: Add Travis

- .ci/appveyor.yml
- .coafile
Add YAMLLintBear in .coafile
and fix issues raised by coala
Fixes #121
> .coafile: Add YAMLLintBear

- README.rst
Change "you will want do" to "you will want to"
Closes https://github.com/coala/coala-quickstart/issues/81
> README.rst: Fix a typo

- coala_quickstart/generation/Settings.py
- coala_quickstart/generation/SettingsFilling.py
- tests/generation/SettingsFillingTest.py
- tests/test_bears/LanguageSettingBear.py
~~Requires https://github.com/coala/coala/pull/4622 to be merged first~~
^^ relevant commit splitted to #165
> CLI Improvements

- coala_quickstart/coala_quickstart.py
- coala_quickstart/generation/FileGlobs.py
- requirements.txt
- tests/generation/FileGlobs.py
Requires https://gitlab.com/coala/coala-utils/merge_requests/47 to be merged first.
> Autcomplete file paths

- setup.py
* Changes the version to 0.4
* Adds Satwik Kansal as a maintainer
* Changes the Homepage url to https://github.com/coala/coala-quickstart
> setup.py: Release 0.4

- .coafile
Add checks for the shortlog of commit
Closes https://github.com/coala/coala-quickstart/issues/38
> .coafile: Add commit checks

- .ci/appveyor.yml
Fixes https://github.com/coala/coala-quickstart/issues/183
> .ci/appveyor.yml: Upgrade pip & setuptools

- setup.cfg
Fixes https://github.com/coala/coala-quickstart/issues/201
> setup.cfg: Fix pytest deprecation warning

- .ci/appveyor.yml
- test-requirements.txt
Fixes #229,
#228
and
Closes #210
> Preinstall packaging

- coala_quickstart/info_extractors/EditorconfigParsing.py
Closes https://github.com/coala/coala-quickstart/issues/223
> EditorconfigParsing.py: Correct function name

- ISSUE_TEMPLATE.md
This PR adds an issue template, incorporating the changes asked in PR #239.
Closes https://github.com/coala/coala-quickstart/issues/187
> ISSUE_TEMPLATE.md: Add template

- .moban.yaml
- requirements.txt
- test-requirements.txt
Updates pytest-timeout pin.
Related to https://gitlab.com/coala/mobans/issues/40
> test-requirements.txt: Use moban template

- coala_quickstart/Strings.py
- coala_quickstart/coala_quickstart.py
- tests/generation/FileGlobs.py
- tests/interaction/Logo.py
coala_quickstart/Strings.py: Updated GLOB_HELP message and added
PROJECT_DIR_HELP message.
coala_quickstart.py: Displayed help message for project directory
question.
Closes #252
> Remove discrepancy in help message

- .travis.yml
Closes https://github.com/coala/coala-quickstart/issues/307
> .travis.yml: Add ntlk_data in cache directories 

- tests/generation/UtilitiesTest.py
Fixes https://github.com/coala/coala-quickstart/issues/301
> UtilitiesTest.py: Remove dead code

- .ci/appveyor.yml
- .gitignore
- .moban.yaml
- .travis.yml
- coala_quickstart/green_mode/green_mode.py
- requirements.txt
- setup.cfg
- setup.py
- test-requirements.txt
- tests/generation/BearsTest.py
Depends on:
- https://github.com/coala/coala/pull/5706
- https://github.com/coala/coala/pull/5806
- https://github.com/coala/coala/pull/5809
(And it is failing due to the use of https:// in the pip requirements; that will be solved once the above are merged, as then the https:// can be replaced with git+ )
> Use coala-bears master
