coala/coala-quickstart

setup.py
Original specified email no longer available.
Closes https://github.com/coala-analyzer/coala-quickstart/issues/31
=> setup.py: Update email for Adrian Zatreanu

README.rst
The title underline was too short, and needs to be
as long as the title. Otherwise, the markup is questionable.
Fixes https://github.com/coala/coala-quickstart/issues/47
=> README.rst: Fix the title underline

requirements.txt
aafd7bbc introduced usage of get_filtered_bears's new parameter
arg_parser added in https://github.com/coala/coala/commit/56bdf0b23
which was first released in coala 0.9.0
Also update the coala-utils dependency to use `~=` syntax.
=> Require coala~=0.9

tests/generation/Bears.py, tests/generation/FileGlobs.py, tests/generation/Project.py, tests/interaction/Logo.py
Replaced import statements in
* test/generation/Bears.py
* test/generation/FileGlobs.py
* test/generation/Project.py
* tests/interaction/Logo.py
with corresponding from coala_utils.ContextManagers
Fixes https://github.com/coala/coala-quickstart/issues/54
=> Replace coalib.misc.ContextManagers with coala_utils.ContextManagers

.ci/deps.sh
Changed the file .ci/deps.sh so that it doesn't support python3.3
anymore as python3.3 hasn't been supported by coala for a long time.
see https://github.com/coala/coala-quickstart/issues/35
Closes https://github.com/coala/coala-quickstart/issues/57
=> Removed python 3.3 dependency

coala_quickstart/Constants.py, tests/generation/Bears.py
Change the important Bear for python language from
PEP8Bear to PycodestyleBear
Closes https://github.com/coala/coala-quickstart/issues/53
=> Replace PEP8Bear with PycodestyleBear

.coafile
After PEP8Bear run, PycodestyleBear will run and
will find the problems that were not found by PEP8Bear.
Closes https://github.com/coala/coala-quickstart/issues/59
=> .coafile: Added PycodestyleBear

coala_quickstart/generation/Settings.py
The new feature checks for empty ignore fields
in .coafile. If this field has no information
it won't be emitted.
Closes https://github.com/coala/coala-quickstart/issues/63
=> Settings.py: Remove ignore field if it's empty

coala_quickstart/coala_quickstart.py, coala_quickstart/generation/FileGlobs.py, requirements.txt, tests/generation/FileGlobs.py
In CI mode there is no need to ask which files
to ignore, because the process is waiting for an
user to answer.
This commit was originally authored by marian-ald
and later took over by hemangsk.
Closes https://github.com/coala/coala-quickstart/issues/49
(Continues https://github.com/coala/coala-quickstart/pull/71)
=> FileGlobs: Bypass the 'files to ignore' question

circle.yml, test-requirements.txt
Use the same set of package requirements in test-requirements.txt
as used by coala core repository.
Closes https://github.com/coala/coala-quickstart/issues/96
=> circle.yml: Enable codecov

coala_quickstart/coala_quickstart.py, coala_quickstart/generation/Settings.py, tests/generation/Bears.py, tests/generation/SettingsTest.py
Settings.py: Add --allow-incomplete-sections mode
In this running mode, coala-quickstart will not prompt the user to
enter settings of bears in non CI mode.
If this mode is selected with CI mode, then it includes unusable
bears as well in generated coafile, without prompting for settings.
Closes #93
=> Settings.py: Add --allow-incomplete-sections mode

coala_quickstart/coala_quickstart.py
Configures the stream handler of the `logging` module
to be `stdout` to avoid ``ValueError`` while writing
to the log stream.
Fixes https://github.com/coala/coala-quickstart/issues/143
=> coala_quickstart: Fix errors due to logging

requirements.txt
Pin lxml version to 3.6.0 as the recent version
3.8.0 which is required by HTTpolice is causing
the Appveyor builds to fail on 64-bit architecture.
This change temporarily fixes the issue until the
upstream issues are not resolved.
Related to https://github.com/coala/coala-quickstart/issues/166
=> requirement.txt: Pin lxml version

coala_quickstart/generation/Settings.py, tests/generation/SettingsTest.py
The implicit `Default` section inheritance is deprecated and
quickstart needs to generate .coafile with new section styles.
Fixes https://github.com/coala/coala-quickstart/issues/127
=> Settings.py: Generate new style sections

coala_quickstart/generation/Bears.py
Silences CLI warnings when ".coafile" is absent.
Fixes https://github.com/coala/coala-quickstart/issues/163
Requires https://github.com/coala/coala/pull/4622 to be fixed first
=> Bears: Silence .coafile not found warnings

coala_quickstart/generation/Bears.py, coala_quickstart/generation/InfoCollector.py, tests/generation/Bears.py, tests/test_bears/SomeLinterBear.py
* Adds "Gruntfile.js" to the `collect_info` method in the InfoCollector
module.
* Adds functionality to `filter_relevant_bears` method to suggest bears
based on `LintTaskInfo` extracted from project similar to
`ProjectDependencyInfo`.
Closes https://github.com/coala/coala-quickstart/issues/145
=> Bears.py: Suggest bears based on Gruntfile.js

setup.py
This removes all instances of (code analysis application) from the repo
Fixes https://github.com/coala/coala-quickstart/issues/178
=> Setup.py: Remove retro acronym

coala_quickstart/coala_quickstart.py, tests/generation/Bears.py
Add arguments '-v' and '--version' to the argparser, 
now `coala-quickstart -v` or `coala-quickstart --version` 
can print out the version of coala quickstart
Closes https://github.com/coala/coala-quickstart/issues/147
=> coala_quickstart.py: Add version argument

.ci/deps.sh
Also merge pip installs to reduce chance
of pip failing to install the second set.
Fixes https://github.com/coala/coala-quickstart/issues/192
=> deps.sh: Upgrade pip & setuptools

coala_quickstart/coala_quickstart.py, coala_quickstart/generation/Bears.py, coala_quickstart/generation/Settings.py, tests/generation/Bears.py, tests/generation/FileGlobs.py, tests/generation/SettingsFillingTest.py
This removes every use of LogPrinter.
Also, it replaces use of LogPrinter into
logging.getLogger() or None.
Closes https://github.com/coala/coala-quickstart/issues/158
=> quickstart: Remove uses of LogPrinter

.coafile
Ignore pycodestyle errors that occur due to a newer version.
Closes https://github.com/coala/coala-quickstart/issues/216
=> .coafile: Ignore pycodestyle errors

README.rst
Change from using the `--pre` tag to git clone, cd into the
directory and then use `pip3 install .`.
Closes https://github.com/coala/coala-quickstart/issues/218
=> README.rst: Change instructions for dev version

coala_quickstart/coala_quickstart.py, coala_quickstart/generation/Bears.py, coala_quickstart/generation/SettingsClass.py, coala_quickstart/generation/Utilities.py, tests/generation/Bears.py, tests/generation/SettingsClassTest.py, tests/generation/UtilitiesTest.py, tests/test_bears/AllKindsOfSettingsBaseBear.py, tests/test_bears/AllKindsOfSettingsBaseDecoratedBear.py, tests/test_bears/AllKindsOfSettingsDependentBear.py, tests/test_bears/AllKindsOfSettingsDependentDecoratedBear.py, tests/test_bears/BearA.py, tests/test_bears/BearB.py, tests/test_bears/BearC.py
* SettingsClass.py: Add function `get_all_args`, get_default_args`,
`search_for_orig`, implement classes `BearSettings` and
`SettingTypes`, add function `collect_bear_settings`.
* coala_quickstart.py: Add the tag for --green-mode, disable all
other modes if green mode is activated and call
`collect_bear_settings` to get the metadata of types of bear
settings.
* Bears.py: Return all candidate bears if green mode is activated.
Closes https://github.com/coala/coala-quickstart/issues/241
=> Implement BearSettings class for type of settings

coala_quickstart/generation/Bears.py
This fixes the typo and changes
it from selectecd_bears --> selected_bears.
Fixes https://github.com/coala/coala-quickstart/issues/240
=> Fix a typo

coala_quickstart/generation/SettingsClass.py, setup.py, tests/generation/SettingsClassTest.py, tests/test_bears/BearC.py, tests/test_bears/LinterBearWithCreateArguments.py, tests/test_bears/LinterBearWithParameters.py
Remove argument `function_name` being passed around but not used in
many places.
Parse generate_config() method too and sort out its settings
if present in a linter bear.
AnotherLinterBear.py     : Create a test linter bear which has the
method generate_config().
YetAnotherLinterBear.py: Create another test linter bear as the
already present linter bears had nothing to
test against.
SettingsClassTest.py      : Add tests for the changes made in code.
=> GREEN_MODE: New set of changes

coala_quickstart/Constants.py, coala_quickstart/generation/Project.py, coala_quickstart/generation/Utilities.py, tests/generation/UtilitiesTest.py
Add a get_language_from_hashbang function
which checks whether hashbang exists in a
file and returns the language used in that
file.
This get_language_from_hashbang()
is used in split_by_language()
and language_percentage()
Fixes #45
=> Utilites.py: Add language detection from hashbang

coala_quickstart/generation/FileGlobs.py, coala_quickstart/generation/Utilities.py, tests/generation/FileGlobs.py
This enables us to look for .gitignore files
recursively in the subdirectories starting
from root.
Closes https://github.com/coala/coala-quickstart/issues/108
=> FileGlobs.py: Recursively look for gitignore files

coala_quickstart/generation/Settings.py
The local variables all_files and gitignore_files were redundant
Hence they were removed.
Closes https://github.com/coala/coala-quickstart/issues/264
=> Settings.py: Unused variables removed

coala_quickstart/Constants.py, coala_quickstart/generation/Bears.py, tests/generation/BearsTest.py
* Constants.py: Add a list GREEN_MODE_INCOMPATIBLE_BEAR_LIST.
* Bears.py: Remove bears from REQUIRED_BEAR_LIST that are present
in GREEN_MODE_INCOMPATIBLE_BEAR_LIST when running
green_mode.
Add tests for the same.
=> Add green mode incompatible bears list

coala_quickstart/Constants.py, coala_quickstart/coala_quickstart.py, coala_quickstart/generation/Project.py, tests/generation/BearsTest.py, tests/generation/ProjectTest.py
* The interactive mode of coala-quickstart now asks to select
languages too.
* The green_mode of coala-quickstart also asks to
select languages by default. This behaviour can be overridden
by the use of the non_interactive tag.
* Two new arguments are introduced max_args and max_values to be
used along side the green_mode to specify the maximum amount
of optional settings for the bears to test against and the
maximum values that can be guessed against each optional setting
respectively.
* Other minor changes include refactoring of some variables from
global to local scope and addition of tests.
=> Project.py: Ask to select languages

.ci/appveyor.yml, .moban.yaml, requirements.txt
The upstream issue https://bugs.launchpad.net/lxml/+bug/1704707
with lxml regarding missing wheel on Winows is fixed now.
Related to https://github.com/coala/coala-quickstart/issues/166
=> requirements.txt: Unpin lxml version

coala_quickstart/green_mode/green_mode.py, tests/green_mode/green_modeTest.py
Python 3.4 and 3.5 fail under our pytest configuration
when the number of jobs is the cpu count - 1.
On Python 3.4, an extra cpu needs to be reserved for the tests
to operate smoothly on CI, and on Python 3.5 and Windows,
multiprocessing needs to be disabled entirely.
Expose argument jobs throughout green_mode, so that it
can be also exposed to the user or test suite for more
controlled use and testing.
Related to https://github.com/coala/coala-quickstart/issues/295
=> green_mode: Choose job count based on environment

tests/green_mode/green_modeTest.py
This change removes test_unified_results from test_bear_test_fun_2.
The expected results of unified_results are [None, None], so
test_unified_results can be removed.
Closes https://github.com/coala/coala-quickstart/issues/302
=> green_modeTest.py: Remove test_unified_results

.nocover.yaml, coala_quickstart/generation/Project.py, coala_quickstart/generation/Utilities.py, setup.cfg, tests/generation/UtilitiesTest.py
When attempting to determine language based on hashbang,
files which can not be opened as Unicode should be ignored.
Fixes https://github.com/coala/coala-quickstart/issues/293
=> generation/: Ignore files which are not unicode

test-requirements.txt
Syncs the templates of this repo.
=> Sync templates

.ci/appveyor.yml, .gitignore, coala_quickstart/green_mode/green_mode.py, setup.cfg, setup.py, test-requirements.txt
And is the minimal fixes needed to make the tree green again, which is failing because of xdist and six
https://travis-ci.org/coala/coala-quickstart/builds/
This depends on https://gitlab.com/coala/mobans/merge_requests/128
It also solves part of https://github.com/coala/coala-quickstart/issues/295
=> Remove pytest-xdist and fix coverage
